import Head from 'next/head'
import { motion as m } from 'framer-motion'

export default function Home() {
  return (
    <m.div
      initial={{ y: '100%' }}
      animate={{ y: '0%' }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      exit={{ opacity: 1 }}
      className='text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-100 lg:px-48 px-16'
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <div className='my-96 p-1'>
          <h1 className='text-6xl text-center lg:text-right lg:text-9xl'>novalarrg</h1>
        </div>
        <div className='flex justify-between'>
          <div>
            <h2>Designer UI</h2>
            <h2>Front End Developer</h2>
            <h2>2022</h2>
          </div>
          <div>
            <h3>Ngodinglah maka kamu akan menemukan hall yang menarik dalam hidup</h3>
            <h3>Design akan membuat kamu lebih berwarna</h3>
            <h3>Temukan teman kodingmu</h3>
          </div>
        </div>
      </main>
    </m.div>
  )
}
